#!/bin/bash

echo '$0 is ' $0

if [ "$1" = "" ]
then
    echo "Error: Please enter an argument"
    exit 1
fi

if [ $# -lt 2 ]
then
    echo "Error: Please enter at least two arguments"
    exit 2
fi

echo "You entered $# arguments, they are:"
for arg in "$@"
do
    echo $arg
done

