#!/bin/bash

# if "$1" is an empty string
if [ "$1" = "" ]
then
    echo Requires at least one argument
    exit 1
fi

grep -i "$1" cars > /dev/null
if [ $? -ne 0 ]
then
    echo Sorry, $1 is not in the cars file >&2
    exit 1
else
    echo $1 was found in cars
fi


